### ISSUE TITLE
Modernize use trailing return type all over

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#102]
This issue tracks modernization to use trailing return type for subroutines all  over the project.

**Comment by vinniefalco** [comment]
Oh god, really? What a waste of effort...

**Comment by ckormanyos** [comment]
> Oh god, really? What a waste of effort...

That's what I thought at first. But having faced comments regarding non-modern code from several other open source projects, I just said, hey, why not use that modernization? It's in the language.

I know some developers resist the trailing return type, and it doesn't really add any actual value.

So this is not really my project. I did some trailing return types, but ended up deactivating (temporarily) this particular clang-tidy rule.

It's up to Matt (@mborland) if he'd like to persist with it, which I do recommend doing in order to simply be less vulnerable to criticism.

**Comment by ckormanyos** [comment]
To be clear, I will not argue, neither for nor against this one, as I consider myself a guest in this project. Offline chats with Matt went in this direction and Matt can formally decide.
