### ISSUE TITLE
Hit and cover some edges and hard-to-reach lines

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#123]

**Comment by mborland** [comment]
Any idea why `ceil` is showing 0% coverage? https://app.codecov.io/gh/cppalliance/decimal/blob/develop/include%2Fboost%2Fdecimal%2Fdetail%2Fcmath%2Fceil.hpp

There's testing here: https://github.com/cppalliance/decimal/blob/develop/test/test_decimal32_cmath.cpp#L147

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) I've appreciated your maneuver of multiplying `constexpr` non-finite values with some kind of Randomly-Generated-Number. This definitely helpy in a very simple way rto hit some `constexpr`-context-specific lines.

We are running around $90\\%$ now. There are some uncovered lines in `decimal32` that I'm having a tough time reaching. But honestly our coverage, considering this early point in the project is EXCELLENT.

We are on target for a hundred in a while.

**Comment by ckormanyos** [comment]
> idea why `ceil` is showing

I think we are hitting a lot of `ceil`now. There are a few lines that we haven't yet reached. But it's [a lot higher](https://app.codecov.io/github/cppalliance/decimal/blob/develop/include%2Fboost%2Fdecimal%2Fdetail%2Fcmath%2Fceil.hpp) than $0\\%$ now.

**Comment by ckormanyos** [comment]
Handled by #170 and #173 and #175 and #208
