### ISSUE TITLE
Why is 03 and 11 all over the place running in ci.yml

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#223]
Hi Matt (@mborland) in YAML ci.yml, we find `03` and `11`in lots of places in the CI-matrices for the runs. Should we eliminate all instances of these?

**Comment by ckormanyos** [comment]
I noticed things like these entries [here](https://github.com/cppalliance/decimal/blob/4d6af6e8035ef13c30734a57dc993ffe1ac6d22b/.github/workflows/ci.yml#L210).

**Comment by mborland** [comment]
They are effectively no-op since the test jamfile requires all the C++14 features. They can be deleted or left.

**Comment by ckormanyos** [comment]
> They can be deleted or left.

After deciding for C++14, I'd rather delete them.

I find that UBSAN is takinga while. Maybe we might need to split it up into a few separate matrices (with fewer standards or even only one standard) per matrix.

**Comment by ckormanyos** [comment]
This is irrelevant. Leave it alone. Otherwise we need to change all kinds of names in the branch protection. It's a bit counter-intuitive, but whatev.
