### ISSUE TITLE
Cast decimal64 to built-in double returns 0 for edge bit patterns

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#242]
Hi Matt (@mborland)

While adapting the `exp()` tests in prototype work using the brand new implementation of `decimal64`, I've ran across what appears to be an edge case.

For some bit patterns stored in `decimal64`, the conversion to built-in 64-bit `double` results in zero for the `double` result. This is happening in the range of $9.98{\times}10^{15}$, so right around that 53-54 bit area.

I have isolated an exact test case, as shown in its entirety below. I use crazy direct-memory-access to initialize what appears to be a valid `decimal64` with the bit pattern `0x6A3B71802C99CB39`. This results in a seemingly valid `decimal64`.

But when casting it to 64-bit built-in double, the result is zero. I included in the comments of the test program a few other bit patterns also featuring this issue.

I ran across these issues when hammering `exp()` tests and every now and then, the values of `exp(x)` for $x{\sim}36$ revealed this problem when computing the closeness to the expected answer. Further investigations showed, in fact, that the `static_cast` to `double` was getting messed up.

I originally detected on MSVC 142 and subsequently also find this on GCC-11 Ubuntu Jammy on WSL.

```cpp
#include <iostream>

#include <boost/decimal.hpp>

// cd /mnt/c/Users/User/Documents/Ks/PC_Software/Test
// g++ -w -O2 -I/mnt/c/MyGitRepos/cppalliance/decimal/include -I/mnt/c/boost/boost_1_83_0 test.cpp -o test.exe

auto main() -> int
{
  // Consider the following integral patterns potentially stored
  // in a given decimal64.

  // 0x6A3A25E507BB83D9
  // 0x6A3800D0288A63E9
  // 0x6A380BF1150D7F35
  // 0x6A3B71802C99CB39

  // Let's take the fourth one of these patterns.
  const std::uint64_t ui = UINT64_C(0x6A3B71802C99CB39);

  // And we convert it via direct-memory access to a decimal64.

  // In this particular example we assume that this number could
  // be the result of some calculation, initialization or any other
  // valid operations.

  const boost::decimal::decimal64 dec = *reinterpret_cast<const boost::decimal::decimal64*>(&ui);

  // Let's print this decimal64 value.
  std::cout << "dec: " << dec << std::endl;

  // Now let's convert this decimal64 value to built-in double.
  // ISSUE: This cast seems to result in 0.
  const double dbl = static_cast<double>(dec);

  std::cout << "dbl: " << dbl << std::endl;
}
```

**Comment by ckormanyos** [comment]
Limitations related to this reflected in #243

**Comment by mborland** [comment]
It looks like you managed to hit one of the edge cases not handled here:
https://github.com/cppalliance/decimal/blob/develop/include/boost/decimal/detail/fast_float/compute_float64.hpp#L176

I'll have to port the real fast float which does arbitrary precision arithmetic to correctly round when that happens.

**Comment by ckormanyos** [comment]
> looks like you managed to hit one of the edge cases

Ahhh. uUnderstood. Thanks Matt.

> have to port the real fast float which does arbitrary precision arithmetic to correctly round

Which relates to one of my questions in the back of my mind. Do you want to consider using parts of Multiprecision such as `cpp_bin_float`? Or is that, as i might suspect, too heavy and not _standalone_ enough?

**Comment by mborland** [comment]
> 
> > have to port the real fast float which does arbitrary precision arithmetic to correctly round
> 
> Which relates to one of my questions in the back of my mind. Do you want to consider using parts of Multiprecision such as `cpp_bin_float`? Or is that, as i might suspect, too heavy and not _standalone_ enough?

We can if necessary. Dr. Lemire packaged a simple big int into fast_float. I have everything ported into charconv. I just need to make sure it is constexpr and add the proper bindings here. The library is here: https://github.com/fastfloat/fast_float

**Comment by ckormanyos** [comment]
> a simple big int into fast_float

Have you considered my own `wide_integer`? It's `constexpr`, single-file header-only, rather efficient and has seen quite a bit of hammering...

**Comment by mborland** [comment]
> > a simple big int into fast_float
> 
> Have you considered my own [`wide_integer`](https://github.com/ckormanyos/wide-integer)? It's `constexpr`, single-file header-only, rather efficient and has seen quite a bit of hammering...

We could give it a try.

**Comment by ckormanyos** [comment]
> We could give it a try.

I could help if you'd like to püursue this. `eide_integer` _might_ or could be up to this challenge. It could at least save some time preliminarily until we get something potentially more well-suited running. It's BSL and you only need to grab the file [uintwide_t.h](https://github.com/ckormanyos/wide-integer/blob/master/math/wide_integer/uintwide_t.h).

This file also has the _honor_ of being, I believe, the oldest living C++ file that I still personally maintain ...

**Comment by ckormanyos** [comment]
We could cut out all the uneeded stuff like GCD, LCM, Miller-Rabin, uniform-wide-int-distribution, etc. and the other number theoretical functions in, like, ten minutes and set the right configuration switches, as there are several of them.

**Comment by ckormanyos** [comment]
Awesome. I will re-establish the `exp()` edge tests that brought this behavior to light...
