### ISSUE TITLE
3.6.7 Elementary Functions

### ISSUE THREAD

**Issue by mborland** [cppalliance/decimal#27]
This can be broken down for all of the required support:

- [x] #366
- [x] ceil
- [x] floor
- [x] #365
- [x] #89
- [x] fmod
- [x] #367
- [x] #138
- [x] #79
- [x] #372
- [x] fabs
- [x] #80
- [x] #111
- [x] #71
- [x] #140
- [x] #277
- [x] #139
- [x] #76
- [x] #132
- [x] #85
- [x] #296
- [x] fpclassify
- [x] isinf 
- [x] isnan
- [x] isfinite   
- [x] isnormal 
- [x] issingaling 
- [x] signbit   

and then the former TR1 functions:

- [x] #167
- [x] #146
- [x] #166
- [x] #90
- [x] #168
- [x] #62
- [x] #350
- [x] fmax
- [x] copysign   
- [x] fmin
- [x] #356
- [x] #131
- [x] #357
- [x] #86
- [x] #127
- [x] #149
- [x] #281
- [x] #154
- [x] #162
- [x] #153
- [x] #161
- [x] #147
- [x] #375
- [x] #148
- [x] #342
- [x] #152
- [x] #156
- [x] #157
- [x] #81
- [x] #75
- [x] #151
- [x] #160
- [x] scalbn
- [x] scalbln
- [x] #141
- [x] trunc

**Comment by ckormanyos** [comment]
Are `fpclassify` and `cbrt` required? I think they might be in `<cmath>` these days?

**Comment by ckormanyos** [comment]
Ah. My bad. I see that `cbrt` is in the second list.

**Comment by mborland** [comment]
> Are `fpclassify` and `cbrt` required? I think they might be in `<cmath>` these days?

fpclassify, isnan, isinf, isfinitie, isnormal are done and I added them to the list. C supports issignaling which I implemented as well because it can be useful.

**Comment by ckormanyos** [comment]
One of the next stepy will be to adapt elem-funcs to 32/64-bits in their implementations, precisions and tests. I will dive into this as `decimal64` moves forward, ...

Cc: @mborland

**Comment by ckormanyos** [comment]
> next steps will be to adapt elem-funcs to 32/64-bits

Adaptions for 128 bits are planned. Probably simply need to specialize a bunch of stuff. A few tests will need to be modified. Testing depth will be an issue due to increased runtimes at 128 bits.

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) now that `lgamma` is _in_, this might be done. Follow-ups are 128-bit and optimizations, but these might be better suited in new, additional issues as they arise.

Yeah `<cmath>` !!!
