### ISSUE TITLE
Decimal128 Foundation

### ISSUE THREAD

**Issue by mborland** [cppalliance/decimal#283]

**Comment by ckormanyos** [comment]
Matt (@mborland) are you considering adding `decimal128`? Then I'd need to up the series expansions and depth of some `<cmath>` funcs. No problem, but if 128 is coming, I'd like to know...

**Comment by mborland** [comment]
I am working it. Hopefully by the end of the week the constructors will all exist. May take a minute to get add, sub, mul, and div right. 

Digits10 for the type is 34 so it may be worthwhile to specialize most of the cmath functions like <quadmath> does for __float128.

**Comment by ckormanyos** [comment]
> I am working it.

Excellent. I like the challeng, ... and the completeness. Makes this application less vulnerable for reference work.

> Digits10 for the type is 34 so it may be worthwhile to specialize most of the cmath functions

Yes. And I will _significantly_ reduce testing depth to 1 or 2 single points in various ranges for all funcs at 128-bits. I'm not intending to add significant amounts of testing time for 128 but do intend to maintain the excellent auality we already have.

A lot of my impls were done for scalability with series so for the most part either i just speicalize the coef tables or specialize the offset from `crend()` that starts the `fma()`-type expansions. So no real worries on major work (as it will be limited) for `<cmath>` at 128-bits.
