### ISSUE TITLE
Phase of sin()

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#293]
The phase of `sin()` seems to be incorrect for at least one point on the negative, real axis.

See the snippet below. I can go through `sin()` and `cos()` and do more complete testing and repair if needed?

```cpp
// Copyright 2023 Christopher Kormanyos
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

#include <iostream>

#include <boost/decimal.hpp>

auto main() -> int
{
  using std::sin;

  std::cout << sin(boost::decimal::decimal32 { 32, -1 }) << std::endl;
  std::cout << sin(-3.2F) << std::endl;
}
```

**Comment by mborland** [comment]
Sure. Right now the test for both is a uniform real distribution from -2pi, 2pi in test_cmath.

**Comment by ckormanyos** [comment]
> Sure. Right now the test for both is a uniform real distribution from -2pi, 2pi in test_cmath.

I'll fix whatever I find...

**Comment by mborland** [comment]
Would you be willing to check `cos()` too? I expect it'll have the same error

**Comment by ckormanyos** [comment]
> Would you be willing to check `cos()` too? I expect it'll have the same error

Of course, I intend to do that.

I have also noticed a problem (even with my fixed `sin()` function) for $x {lesssim} -30$ and $x {gtrsim} 30$. I'll be checking that too.
