### ISSUE TITLE
Adapt Wide-Integer Repo for use as Backend

### ISSUE THREAD

**Issue by mborland** [cppalliance/decimal#355]
https://github.com/ckormanyos/wide-integer/tree/master now supports constexpr at C++14. Can potentially replace our unoptimized 128-bit and 256-bit integer classes.

**Comment by ckormanyos** [comment]
Hi @mborland as an intermediate step, I will attempt to isolate the long-division routine and rework it to use limbs as in wide-integer. This is tough, but if it succeeds, might help significantly.

Note: Reverse limbs and restrice to 32-bit limbs via conversion(s) at input/output to long division.

**Comment by ckormanyos** [comment]
At the moment, only Knuth long division is actually needed (and/or) significantly helpful.

I'll just go ahead and close this as handled via #387.

Cc: @mborland
