### ISSUE TITLE
More funcs finish ldexp/frexp and add fpclassify and more

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#51]

**Comment by mborland** [comment]
If you look on develop I added a folder today to house each cmath function by itself. I think it's a bit cleaner than making them all friends unless it's easier (like isneg, fpclassify, etc.)

**Comment by ckormanyos** [comment]
> added a folder today to house each cmath function by itself. I think it's a bit cleaner than making them all friends...

Yes indeed. Thank you Matt.
I'll follow this style for most functions and move the ones I just made where appropriate.

**Comment by ckormanyos** [comment]
This will be handled in #27
