### ISSUE TITLE
uint256_t multiplication is incorrect

### ISSUE THREAD

**Issue by mborland** [cppalliance/decimal#559]
@ckormanyos I am trying to improve the calculation for `num_digits` by pre-computing a binary search tree rather than doing repeated division for large types. The code for the generation is:

```
template <typename T, std::size_t N>
constexpr auto generate_array() noexcept -> std::array<T, N>
{
    std::array<T, N> values {};

    values[0] = T{1};
    for (std::size_t i {1}; i < N; ++i)
    {
        values[i] = values[i - 1] * UINT64_C(10);
    }

    return values;
}
```

For `uint256_t` the call is `constexpr auto powers_of_10 = generate_array<boost::decimal::detail::uint256_t, 79>();`. Using that tree I got a ton of failiures in basic operations. The debugger shows the below values in the array for example (i = 53, 54, ...):

<img width="353" alt="Screenshot 2024-05-15 at 9 09 40 AM" src="https://github.com/cppalliance/decimal/assets/3745830/83c9863a-62af-4290-845f-a98231225ee3">

Something seems to be going run on the high word.

**Comment by ckormanyos** [comment]
Hi Matt (@ckormanyos). We talked in offline chats on this. And this might be what's causing "fuzz" around 30 decimal digits and higher in dec-128. . I'll try to get to the bottom of this one.

**Comment by ckormanyos** [comment]
Hi Matt (@mborland) something is going haywire. I am tracking it down in a new branch. Give me a day or two to dial mul-256

Below is a re-posting of similar test code I adapted.

```cpp
#include <array>

#include <boost/decimal.hpp>

template <typename T,
          const std::size_t N>
constexpr auto generate_array() noexcept -> std::array<T, N>
{
  std::array<T, N> values { };

  std::size_t index { 0 };

  values[index] = T { 1 };

  ++index;

  for ( ; index < N; ++index)
  {
    values[index] = values[index - 1] * UINT64_C(10);
  }

  return values;
}

auto main() -> int
{
  using local_uint256_t = boost::decimal::detail::uint256_t;

  constexpr auto powers_of_10 = generate_array<local_uint256_t, static_cast<std::size_t>(UINT8_C(78))>();

  std::size_t idx { };

  for(const auto& ui_val : powers_of_10)
  {
    std::cout << "index: " << idx << ", " << ui_val << std::endl;

    ++idx;
  }
}
```

**Comment by ckormanyos** [comment]
Now cycling in #574.
