### ISSUE TITLE
Explore `decimal32_fast_t`

### ISSUE THREAD

**Issue by mborland** [cppalliance/decimal#570]
As requested by Glen on the Mailing List we should be able to directly address the significand and exponent with only a few extra bits.

**Comment by ckormanyos** [comment]
I would use names similat to those found in `<cstdint>` where we find such names as `std::uint_fast32_t`. I guess that would correspond to something like `boost::decimal_fast32_t`?

**Comment by mborland** [comment]
> I would use names similat to those found in `<cstdint>` where we find such names as `std::uint_fast32_t`. I guess that would correspond to something like `boost::decimal_fast32_t`? Which begs the question, should `boost::decimal32` actually be `boost::decimal32_t`?

The TR has it listed as `decimal32`, `decimal64`, and `decimal128`. The C TR went with `_Decimal32`, `_Decimal64`, and `_Decimal128`. Now that the library is out in the wild I don't want to break the type names. I hadn't really thought about it before
