### ISSUE TITLE
Increase code coverage and maybe add quality gate

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#65]
We have multiple test files each with its own `main()` subroutine. It might actually be straightforward (I think) to increase code coverage by including multiple test files in the coverage action. Maybe we could add a quality gate, but it might be too early for this.

There are some configuration settings in CodeCov that can also be handled as part of this issue. I kind of forgot if there is a _settings_ file or what, but I'll figure it out based on some of my other projects.

When adding files to CodeCov we might need to reduce testing depth since coverage instrumented files tend to run quite slowly. But so far run-time totals have not been a huge problem.

**Comment by mborland** [comment]
CodeCov says we are Missing Base Commit so it is unable to show the diff on a new PR.

**Comment by ckormanyos** [comment]
> CodeCov says we are Missing Base Commit so it is unable to show the diff on a new PR.

Indeed. I saw your recent PR did not get any CodeCov comment from the Bot.

This is one of those things that I've handled before. But forgot exactly how, ... I did this when setting things up in my own repos, but conveniently forgot exactly where what is needed. I'll go through and find out, ... or try to...

**Comment by mborland** [comment]
It looks like it is only updating on `main`, and PR. I think adding `develop` should fix it.

**Comment by ckormanyos** [comment]
> It looks like it is only updating on main, and PR. I think adding develop should fix it.

Oh yes. You do not use the same text string for the main branch. My bad. I will fix in my running PR...

**Comment by ckormanyos** [comment]
See also #67

**Comment by ckormanyos** [comment]
Now cycling for $90\\%$ coverage in #69.

**Comment by ckormanyos** [comment]
My recent push (silly me) discarded header coverage for decimal itself. Matt (@mborland) I'll repair this ASAP...
