### ISSUE TITLE
Ready for branch protection?

### ISSUE THREAD

**Issue by ckormanyos** [cppalliance/decimal#66]
Matt (@mborland) CI is running green and well these days. I would suggest putting branch protectin on the repo. Thoughts?

**Comment by mborland** [comment]
This is what I have right now:

![Screenshot 2023-09-11 at 9 26 26 AM](https://github.com/cppalliance/decimal/assets/3745830/eef6d0f3-70ab-4b9c-885e-c9cbf0898a10)


Are there more that you normally have?

**Comment by ckormanyos** [comment]
> Are there more that you normally have?

Yes. I believe (hope) we are talking about the same thing.

![grafik](https://github.com/cppalliance/decimal/assets/2404721/2dfa3884-91f3-4415-a2b6-c1c7fa7ff8c0)

In the search field of the graphic I've posted, you can enter by search string _ALL_ lf the jobs running on the GHA CI runners. It can be quite laborious to identify each job since we use a lot of test matrices. But basically, you put in a string and the matching jobs come down in a combo box. You then select each GHA CI job and include them as required checks.

**Comment by mborland** [comment]
I also have force push disabled for everyone including admins

**Comment by ckormanyos** [comment]
> I also have force push disabled for everyone including admins

Correct. I also go that way. Agreed.

**Comment by mborland** [comment]
> > Are there more that you normally have?
> 
> Yes. I believe (hope) we are talking about the same thing.
> 
> ![grafik](https://user-images.githubusercontent.com/2404721/266940902-2dfa3884-91f3-4415-a2b6-c1c7fa7ff8c0.png)
> 
> In the search field of the graphic I've posted, you can enter by search string _ALL_ lf the jobs running on the GHA CI runners. It can be quite laborious to identify each job since we use a lot of test matrices. But basically, you put in a string and the matching jobs come down in a combo box. You then select each GHA CI job and include them as required checks.

They should all be marked as required now.

**Comment by ckormanyos** [comment]
> They should all be marked as required now.

Looks good cycling in my PR. Thanks Matt (@mborland).

It sure is tough finding them all in that combo box. I also usually forget to add the new ones as we add/remove required tests in CI. But it works really well once the CI stabilizes...

**Comment by ckormanyos** [comment]
Fixed by #67
